### PR TITLE
[CSL-1766] Improve stylish-haskell config for our needs

### PR DESCRIPTION
**Pull request by gromakovsky**
It was agreed to make these changes to make diffs smaller and reduce
number of merge conflicts.

### CODE REVIEW

**Comment by gromakovsky** [comment]
Note: I will make a PR to cardano-sl a bit later (after something is merged somewhere).

**Comment by gromakovsky** [comment]
heh, I can write something here and trigger huha :trollface:

**Comment by gromakovsky** [comment]
huha

**Comment by jagajaga** [comment]
I disagree.

**Pull request closed without merging**
