### PR TITLE
Add 'colorizeDull' which uses ANSI.Dull palete

### PR DESCRIPTION
**Pull request by gromakovsky**

### CODE REVIEW

**Comment by volhovM** [comment]
What about versioning btw? Do we have any in `serokell-util`?

**Comment by gromakovsky** [comment]
Ok, I've changed version and added changelog.

**Comment by ChShersh** [comment]
@gromakovsky @Martoon-00 @volhovM Btw, what is _dull_? It's not documented in `ansi-terminal` package and I can't google it :disappointed:

**Comment by Martoon-00** [comment]
`Vivid` is plain font
`Dull`is more dark

e.g. `Dull` `White` = gray

**Pull request merged**
