### PR TITLE
Put qualified imports into a separate section

### PR DESCRIPTION
**Pull request by neongreen**

### CODE REVIEW

**Comment by ChShersh** [comment]
@neongreen Is this really necessary? I don't immediately see benefits of accepting this proposal. Could you please explain more about motivation behind this change?

**Comment by neongreen** [comment]
> @gromak Хай, Ванек
>
> У меня к тебе предложение
>
> currently our style guide allows qualified imports. Using qualified imports *more often* would make merges, changing files, etc easier. Putting qualified imports into a *separate section* would make it easier for the reader to immediately see which abbreviations correspond to which names.
> 
> Therefore I propose putting qualified imports into a separate section at the end of imports, as some other big projects are already doing (I saw it in Wire iirc).

**Comment by ChShersh** [comment]
@neongreen In that case, do we want to modify our `stylish-haskell` config for it to no add 11 spaces in section of imports?

**Comment by neongreen** [comment]
Oh, yep, we could do that.

**Comment by ChShersh** [comment]
@neongreen Waiting for your changes regarding _11 spaces_ in `stylish-haskell.yaml` and in `serokell-style-guide.md`.

Btw, what others think about this PR? cc @gromakovsky @Martoon-00 @int-index and others

**Comment by int-index** [comment]
I'd like to see qualified imports in a separate section so unqualified imports don't get aligned like this:

```import                 Module```

I just can't stand these spaces.

**Comment by neongreen** [comment]
> Waiting for your changes regarding 11 spaces in stylish-haskell.yaml and in serokell-style-guide.md.

done

**Comment by neongreen** [comment]
Do you think I should make a PR into CSL, or should we rather wait until the other changes are discussed (e.g. possible removal of explicit imports)?

**Comment by ChShersh** [comment]
@neongreen Well, `stylish-haskell` can't convert explicit imports to implicit. So probably this exact thing can be done lazily. I don't know how you perform such changes for big projects... Better consult with @gromakovsky.

**Pull request merged**
